# Generated by Django 3.1.7 on 2021-04-07 15:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=280)),
                ('stars', models.IntegerField()),
                ('sign_ups', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=3)),
            ],
        ),
        migrations.CreateModel(
            name='Questboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=280)),
                ('stars', models.IntegerField()),
            ],
        ),
    ]
