# Generated by Django 3.1.7 on 2021-04-07 15:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='sign_ups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=3),
        ),
    ]
