# Generated by Django 3.1.7 on 2021-04-07 16:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_auto_20210407_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='max_dibs',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quest',
            name='sign_ups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=None),
        ),
    ]
