# Generated by Django 3.2 on 2021-04-07 18:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_auto_20210407_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='max_dibs',
        ),
        migrations.AddField(
            model_name='quest',
            name='everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quest',
            name='sign_ups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, null=True, size=3),
        ),
    ]
